---
abstract: 'multiplexer to execute subs'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Module::Build::Pluggable::CPANfile: 0.04
configure_requires:
  Module::Build: 0.40
  Module::Build::Pluggable: 0
  Module::Build::Pluggable::CPANfile: 0.04
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Mux
provides:
  Sub::Mux:
    file: lib/Sub/Mux.pm
    version: 0.02
requires:
  Carp: 0
  perl: 5.008005
resources:
  bugtracker: http://github.com/bayashi/Sub-Mux/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Sub-Mux
version: 0.02
x_test_requires:
  Test::More: 0.88
